<?php

/**
 * @file
 * Provides Yale CAS customizations.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alters the user entity form.
 */
function yale_cas_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Alter the user login form.
  $casSettingsService = \Drupal::service('yale_cas.settings');
  $casSettingsService->userFormAlter($form, $form_state);
}
